volumes:
  postgres-data:
  web-certificates:

services:
  db:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    env_file: ./.env
    ports:
      - ${DATABASE_PORT:-}:5432
    container_name: summarize-tg-bot-db
    restart: unless-stopped

  app:
    build: .
    working_dir: /root/app
    env_file: ./.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${DATABASE_NAME}?schema=public
      - CRYPTO_KEY=${CRYPTO_KEY}
    depends_on:
      - db
    volumes:
      - ./logs:/root/app/logs
    container_name: summarize-tg-bot-app
    ports:
      - ${WEBSERVER_PORT}:${WEBSERVER_PORT}
    restart: unless-stopped

  # по умолчанию запускается раз в день
  # backup:
  #   image: prodrigestivill/postgres-backup-local
  #   environment:
  #     - POSTGRES_HOST=db
  #     - POSTGRES_DB=summarize-bot
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   volumes:
  #     - ~/pgbackups/summarize-tg-bot:/backups # путь на хост-компьютере для хранения резервных копий
  #   depends_on:
  #     - db
  #   container_name: summarize-tg-bot-db-backup
  #   restart: unless-stopped

  # logs ui
  # dozzle:
  #   container_name: summarize-tg-bot-dozzle
  #   image: amir20/dozzle:v5.0.5
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - DOZZLE_USERNAME=${DOZZLE_USERNAME}
  #     - DOZZLE_PASSWORD=${DOZZLE_PASSWORD}
  #   ports:
  #     - 9999:8080
  #   restart: unless-stopped

  nginx:
    build: ./nginx
    env_file: ./.env
    environment:
      - NGINX_APP_HOST=${NGINX_APP_HOST:-app}
    volumes:
      - ./certbot/www:/var/www/certbot
      - web-certificates:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    container_name: summarize-tg-bot-nginx
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - web-certificates:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: []
    container_name: summarize-tg-bot-certbot
    restart: unless-stopped
