version: '3.8'

volumes:
  postgres-data:

services:
  db:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #ports:
    #  - 5432:5432
    container_name: summarize-tg-bot-db

  app:
    build: .
    working_dir: /root/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/summarize-bot?schema=public
    depends_on:
      - db
    container_name: summarize-tg-bot-app

  # по умолчанию запускается раз в день
  backup:
    image: prodrigestivill/postgres-backup-local
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=summarize-bot
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ~/pgbackups:/backups # путь на хост-компьютере для хранения резервных копий
    depends_on:
      - db
    container_name: summarize-tg-bot-db-backup
