version: '3.8'

volumes:
  postgres-data:

services:
  db:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 9345:5432
    container_name: summarize-tg-bot-db

  app:
    build: .
    working_dir: /root/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/summarize-bot?schema=public
      - CRYPTO_KEY=${CRYPTO_KEY}
    depends_on:
      - db
    volumes:
      - ./logs:/root/app/logs
    container_name: summarize-tg-bot-app

  # по умолчанию запускается раз в день
  backup:
    image: prodrigestivill/postgres-backup-local
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=summarize-bot
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ~/pgbackups/summarize-tg-bot:/backups # путь на хост-компьютере для хранения резервных копий
    depends_on:
      - db
    container_name: summarize-tg-bot-db-backup

  # logs ui
  dozzle:
    container_name: summarize-tg-bot-dozzle
    image: amir20/dozzle:v5.0.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
